services:
  msr:
    image: ${MSR_CONTAINER_IMAGE}
    hostname: wm-tools-jcode
    volumes:
      # Our Code
      - ../../code/is-packages/WxSimpleConfig/:${GUEST_IS_HOME}/packages/WxSimpleConfig/
      - ../../code/is-packages/WxSimpleConfigTest/:${GUEST_IS_HOME}/packages/WxSimpleConfigTest/
      - ../../code/is-packages/WzPConfig/:${GUEST_IS_HOME}/packages/WzPConfig/
      - ../../code/is-packages/WzPConfigLocalTest/:${GUEST_IS_HOME}/packages/WzPConfigLocalTest/
      - ../../code/is-packages/WzTAssert/:${GUEST_IS_HOME}/packages/WzTAssert/
      - ../../code/is-packages/WzTAssertLocalTest/:${GUEST_IS_HOME}/packages/WzTAssertLocalTest/
      - ../../code/is-packages/WzTDataGen/:${GUEST_IS_HOME}/packages/WzTDataGen/
      - ../../code/is-packages/WzTMocks/:${GUEST_IS_HOME}/packages/WzTMocks/
      - ../../code/is-packages/WzTMocksLocalTest/:${GUEST_IS_HOME}/packages/WzTMocksLocalTest/
      - ../../code/is-packages/WzTTools/:${GUEST_IS_HOME}/packages/WzTTools/
      - ../../code/is-packages/WzTToolsLocalTest/:${GUEST_IS_HOME}/packages/WzTToolsLocalTest/
      # scripts
      - ./scripts/:/mnt/scripts/
    environment:
      - GUEST_IS_HOME
    entrypoint: /mnt/scripts/entrypoint.sh
